package com.monitoring.usv.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VehicleDetailAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleDetailAllPropertiesEquals(VehicleDetail expected, VehicleDetail actual) {
        assertVehicleDetailAutoGeneratedPropertiesEquals(expected, actual);
        assertVehicleDetailAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleDetailAllUpdatablePropertiesEquals(VehicleDetail expected, VehicleDetail actual) {
        assertVehicleDetailUpdatableFieldsEquals(expected, actual);
        assertVehicleDetailUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleDetailAutoGeneratedPropertiesEquals(VehicleDetail expected, VehicleDetail actual) {
        assertThat(expected)
            .as("Verify VehicleDetail auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleDetailUpdatableFieldsEquals(VehicleDetail expected, VehicleDetail actual) {
        assertThat(expected)
            .as("Verify VehicleDetail relevant properties")
            .satisfies(e -> assertThat(e.getColor()).as("check color").isEqualTo(actual.getColor()))
            .satisfies(e -> assertThat(e.getEngineDescription()).as("check engineDescription").isEqualTo(actual.getEngineDescription()))
            .satisfies(e -> assertThat(e.getFuelType()).as("check fuelType").isEqualTo(actual.getFuelType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehicleDetailUpdatableRelationshipsEquals(VehicleDetail expected, VehicleDetail actual) {
        // empty method
    }
}
